#!/bin/bash
if [ -z "$9" ]
then
	echo Not enough arguments...
	echo 8 arguments required
	echo Background, Foreground, Alert, Accent1, Accent1 Alt, Accent2, Accent2 Alt, and Active
fi

for var in "$@"
do 
	if [ $(echo $var | head -c 1) = "#" ] && [ "$var" != "add" ]
	then
			echo $var does not need "#"
	exit;
	elif [ $(expr length "$var") != 6 ]  && [ "$var" != "add" ]
	then
		echo $var is only $(expr length "$var") charcters. Should be 7. 
		exit;
	fi

done

read -p 'Enter Theme Name: ' fileName

if test -f ~/themePicker/themes/"$fileName"
then
	echo Theme "$fileName" already exsists...
	read -p 'Do you want to overwrite the theme? ' ans
	if [ "$ans" = "y" ] || [ "$ans" = "yes" ]
	then
		rm ~/themePicker/themes/$fileName
	else 
		read -p 'Enter different name for the new theme: ' fileName
	fi
fi

for colors in "$@"
do 
	echo '#'$colors | tee -a ~/themePicker/themes/$fileName > /dev/null
done

